<!DOCTYPE html>

<html lang="vi" prefix="og: http://ogp.me/ns#">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="prerender" href="../index.html" />



    <title>Đường Sắt Việt Nam</title>



    <style type="text/css">
        img.wp-smiley,
        img.emoji {
            display: inline !important;
            border: none !important;
            box-shadow: none !important;
            height: 1em !important;
            width: 1em !important;
            margin: 0 .07em !important;
            vertical-align: -0.1em !important;
            background: none !important;
            padding: 0 !important;
        }
    </style>

    <style type="text/css">
        .breaking-news-ticker {
            border-radius: 0px;
            border-style: solid;
            border-width: 0px;
            border-color: #259648;
            background-color: #259648;
        }

        .breaking-news-ticker ul li a,
        .breaking-news-ticker ul li a:link {
            color: #FFFFFF;
            font-size: 16px;
        }

        div.breaking-news-ticker .breaking-news-ticker-title {
            font-size: 15px;
            color: #FFFFFF;
            background-color: #259648;
        }

        div.breaking-news-ticker .breaking-news-ticker-title span {
            border-color: transparent transparent transparent #259648;
        }

        .breaking-news-ticker .controls {
            top: 5px;
        }

        .breaking-news-ticker .entry-meta {
            color: #FFFFFF;
        }

        .breaking-news-ticker .controls span {
            background-color: #217d3d
        }
    </style>

    <!--styles generated by site options-->
    <style type='text/css'>
        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        .page-banner-heading,
        footer .foot-heading {
            font-family: 'Roboto', Arial, sans-serif;
            font-weight: 400;
        }

        #tt-boxed-layout {
            -moz-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);
            -webkit-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);
            box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);
        }

        .top-aside {
            padding: 8px 0;
        }

        .small_banner {
            padding: 25px 0;
        }

        .footer-content {
            padding: 20px 0;
        }

        header {
            padding: 10px 0;
        }
    </style>
    <noscript>
        <style type="text/css">
            .wpb_animate_when_almost_visible {
                opacity: 1;
            }
        </style>
    </noscript>
</head>

<body class="single single-post postid-686 single-format-standard wpb-js-composer js-comp-ver-4.11.2.1 vc_responsive">
    <div id="tt-wide-layout">
        <div id="tt-header-wrap">

            <aside class="top-aside clearfix">
                <div class="center-wrap">
                    <div class="one_half">
                        <div class="sidebar-widget widget_text">
                            <div class="textwidget">
                                <ul class="list">
                                    <li style="font-weight: 700;
    font-size: 16px;">Tổng đài vé Online:<a href="tel:19001730" style="font-weight: 700;
    font-size: 16px;"> 1900 1730</a></li>
                                </ul>
                            </div>
                        </div>
                    </div><!-- end .top-toolbar-left -->

                    <div class="one_half">
                        <div class="sidebar-widget widget_text">
                            <div class="textwidget">
                                <div class="social-top">
                                    <ul>
                                        <li>
                                            <a href="https://www.facebook.com/DailyvexeHaNoiVinh"><i class="fa fa-facebook"></i><br />
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://twitter.com"><i class="fa fa-twitter"></i><br />
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://www.google.com.vn/"><i class="fa fa-google-plus"></i><br />
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://www.youtube.com/channel/UCVGN2liHOox8Ob8sbb88qhQ?view_as=subscriber"><i class="fa fa-youtube"></i><br />
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div><!-- end .top-toolbar-right -->
                </div><!-- end .center-wrap -->
                <div class="top-aside-shadow"></div>
            </aside>

            <header>
                <div class="center-wrap">
                    <div class="companyIdentity">
                        <a href="http://localhost/project/"><img src="wp-content/uploads/2018/05/dsvn1.png" alt="Tàu Bông Sen Vàng" /></a>
                    </div><!-- end .companyIdentity -->
                    <nav>
                        <ul id="menu-main-nav">
                            <li id="menu-item-570" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children menu-item-570"><a href="#">Dịch Vụ</a>
                            </li>

                        </ul>
                    </nav>
                </div><!-- end .center-wrap -->
            </header>
        </div><!-- END #tt-header-wrap -->
        <section class="small_banner">
            <div class="center-wrap banner-no-crumbs">
                <p class="page-banner-heading"></p>

            </div><!-- end .center-wrap -->
            <div class="shadow top"></div>
            <div class="shadow bottom"></div>
            <div class="tt-overlay"></div>
        </section>

        <section id="content-container" class="clearfix">
            <div id="main-wrap" class="main-wrap-slider clearfix">
                <div class="row-in">
                    <div class="page_content blog_page_content right-content">

                        <div id="post-686" class="post-686 post type-post status-publish format-standard has-post-thumbnail hentry category-khong-phan-loai tag-gioi-thieu-chung tag-xe-phuc-loi">
                            <article class="preview blog-main-preview">
                                <h2 class="entry-title"><a href="#" title="CHÍNH SÁCH HỦY VÉ">CHÍNH SÁCH HỦY VÉ</a></h2>
                                <div class="top-sharing clearfix">
                                    <div class="tt-share clearfix">

                                    </div><!-- end .tt-share -->
                                    <p style="text-align: justify;"><a href="../index.html">Đường Sắt Việt Nam</a> – Tàu chất lượng cao chuyên tuyến <strong>Hà Nội </strong> và <strong>Các tỉnh thành</strong>.</p>
                                    <p style="text-align: justify;">Chính sách hủy vé đối với vé đặt thông qua website:<br>
                                        • Trong 1 tiếng trước giờ khởi hành: phí huỷ vé là 100%<br>
                                        • Từ 1 tiếng đến 12 tiếng trước giờ khởi hành: phí hủy vé là 80%<br>
                                        • Từ 12 tiếng đến 24 tiềng trước giờ khởi hành: phí huỷ vé là 50%<br>
                                        • Từ 1 ngày đến 3 ngày trước giờ khởi hành: phí huỷ vé là 10%<br>
                                        • Trên 3 ngày trước giờ khởi hành: phí hủy vé là 5%<br>
                                        Phí hủy vé được áp dụng đối với giá vé gốc, không áp dụng cho giá vé sau khi đã giảm giá. Chi phí phạt hủy vé được trích từ tiền vé đã thanh toán hoặc giảm giá và phần tiền còn lại sẽ được hoàn trả. Ví dụ: Nếu giá vé gốc là VND200,000 và giá vé sau khi giảm giá của bạn là VND150,000, chi phí phạt hủy được tính trên giá vé gốc, trong trường hợp này là VND200,000. Vì vậy, nếu chi phí hủy vé là 10%, số tiền hoàn trả của bạn sẽ là 150,000 – 20,000 = VND130,000.<br>
                                        Việc hủy một phần vé hoặc hoãn lại chuyến đi không thể được thực hiện sau khi vé được xác nhận.<br></p>
                                    <p style="text-align: justify;">Hoặc liên hệ hotline:</p>
                                    <p style="text-align: justify;">Tại Hà Nội: 0988 994 223</p>
                                    <p style="text-align: justify;">Mua vé trực tuyến: <a href="https://dsvn.vn">https://dsvn.vn</a>. Hotline: 19006469</p>
                                    <div class="tt-share clearfix">


                                        <span class="facebook-share">

                                            <div class="fb-like" data-href="http://taubongsenvang.vn/gioi-thieu-chung/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>

                                        </span>
                                        <div class="page_content blog_page_content right-content">

                                            <div id="post-686" class="post-686 post type-post status-publish format-standard has-post-thumbnail hentry category-khong-phan-loai tag-gioi-thieu-chung tag-xe-phuc-loi">
                                                <article class="preview blog-main-preview">
                                                    <h2 class="entry-title"><a href="#" title="Khuyễn Mãi">Khuyến Mãi</a></h2>
                                                    <div class="top-sharing clearfix">
                                                        <div class="tt-share clearfix">

                                                        </div><!-- end .tt-share -->
                                                        <p style="text-align: justify;"><a href="../index.html">Đường Sắt Việt Nam</a> – Tàu chất lượng cao chuyên tuyến <strong>Hà Nội </strong> và <strong>Các tỉnh thành</strong>.</p>
                                                        <p style="text-align: justify;">Các chính sách giảm giá vé giai đoạn sau Hè 2019:<br>
                                                            Kể từ ngày 1/6/2019, Công ty CP Vận tải Đường sắt Hà Nội giảm giá vé tàu khách Thống nhất, Khu đoạn (không kể ngày Lễ, Tết) từ 10% đến 40% so với giá vé Hè 2018. Ngoài ra, từ 04/7/2019 đến 26/12/2019 giảm thêm 10% giá vé đối với các loại chỗ trên các đoàn tàu Thống Nhất.
                                                            Hàng ngày, Công ty CP Vận tải Đường sắt Hà Nội tổ chức chạy 03 đôi tàu Thống nhất giữa Hà Nội – Tp Hồ Chí Minh và ngược lại. Ngoài ra, Công ty CP Vận tải Đường sắt Hà Nội còn tổ chức các đôi tàu chạy hàng ngày các tàu khu đoạn trên các tuyến:
                                                            Hà Nội – Đà Nẵng: 1đôi tàu;
                                                            Hà Nội- Vinh: 2 đôi tàu
                                                            Hà Nội – Lào Cai: 2 đôi tàu
                                                            Hà Nội – Yên Bái: 1 đôi tàu
                                                            Hà Nội – Hải Phòng: 4 đôi tàu
                                                            Trong dịp nghỉ lễ 2/9, ngoài các chuyến tàu chạy thường xuyên hàng ngày, Công ty CP Vận tải Đường sắt Hà Nội còn tổ chức tăng thêm tàu và nối thêm xe trên các tuyến. Công ty tổ chức chạy tổng cộng gần 140 đoàn tàu khách với 90.000 chỗ trong đó có hơn 60 chuyến tàu với 45.000 chỗ để phục vụ nhu cầu hành khách đi Vinh, Đồng Hới, Huế, Đà Nẵng. Ngoài ra, nếu nhu cầu của hành khách tăng cao, Công ty sẽ tổ chức chạy thêm tàu để phục vụ hành khách.</p>
                                                        <p style="text-align: justify;">Hoặc liên hệ hotline:</p>
                                                        <p style="text-align: justify;">Tại Hà Nội: 0988 994 223</p>
                                                        <p style="text-align: justify;">Mua vé trực tuyến: <a href="https://dsvn.vn">https://dsvn.vn</a>. Hotline: 19006469</p>
                                                        <div class="tt-share clearfix">


                                                            <span class="facebook-share">

                                                                <div class="fb-like" data-href="http://taubongsenvang.vn/gioi-thieu-chung/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>

                                                            </span>


                                                        </div><!-- end .tt-share -->
                                                </article><!-- end .blog-main-preview -->
                                            </div><!-- end #post-ID -->



                                        </div><!-- end .page_content -->


        </section><!-- END content-container -->



    </div><!-- end .center-wrap -->

    </div><!-- end .footer-copyright -->




    <div class="shadow top"></div>

    <div class="tt-overlay"></div>

    </footer>


    </div><!-- end .tt-wide-layout -->



    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery("#main-bnt").easyTicker({
                direction: 'up',
                speed: 500,
                interval: 3000,
                height: 'auto',
                visible: 1,
                mousePause: 1,
                controls: {
                    down: '#prev-btn',
                    up: '#next-btn'
                }
            });
        });
    </script>



    <script type="text/javascript">
        jQuery(document).ready(function($) {

            // Homepage slider setup. Issued in the footer to accept user-set variables.

            $('#slides').slides({

                preload: false,

                //preloadImage: 'http://files.truethemes.net/themes/sterling-wp/ajax-loader.gif',

                autoHeight: true,

                effect: 'slide',

                slideSpeed: 500,

                play: 0,

                randomize: false,

                hoverPause: false,

                pause: 0,

                generateNextPrev: false
            });



            // Allows for custom nav buttons to remain outside of #slides container.

            $('.banner-slider .next').click(function() {

                $('#slides .next').click();

            });

            $('.banner-slider .prev').click(function() {

                $('#slides .prev').click();

            });

        });
    </script>